# Change these first
owner: ANYB0DYTH3R3
repo: all-website-status

sites:
  - name: Main Site
    url: https://not-games.netlify.app/
  - name: Beta Site
    url: https://huntervtharp1018.wixsite.com/unblocked-games
  - name: AI Chat Service
    url: https://nextjs-chat3-nine.vercel.app/
  - name: Fluffy Cupcake
    url: https://fluffy-cupcake-74f27a.netlify.app/
  - name: HT's UB Games
    url: https://unblock-my-stuff.netlify.app/
  - name: KP's GBA Games
    url: http://watch-ewing-block-this.netlify.app/
  - name: 3kh0
    url: https://bright-wisp-83d563.netlify.app/
    - name: Absolutely Nothing
    url: https://123-do-not-block-me.netlify.app/
    - name: Minecraft
    url: https://hey-ewing-this-is-not-minecraft.netlify.app/
    - name: We Game
    url: http://we-game.netlify.app/
    - name: Web Chat (beta)
    url: https://web-chat-app-brown.vercel.app/
    port: 80
    check: "tcp-ping"
    ipv6: true

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
